### ISSUE TITLE
More ORACLE Error ORA-01723: zero-length columns are not allowed #309

### ISSUE THREAD

**Issue by mgweiner** [OHDSI/Achilles#317]
The fix to Issue 309 addressed the zero-length column issue in the various SQL files within the Achilles\sql\sql_server\analyses directory.

Unfortunately, there are additional sql statements with a similar problem within the
 
Achilles\sql\sql_server\post_processing\concept_hierarchy.sql file

and all the files in the 
Achilles\sql\sql_server\post_processing\concept_hierarchies directory

**Comment by alondhe** [comment]
Hi @mgweiner -- can you try the version I pushed to my fork:

`devtools::install_github("alondhe/Achilles")`

**Comment by t-abdul-basser** [comment]
Thanks @alondhe!

**Comment by mgweiner** [comment]
I ran the new version of the Achilles code (1.6.1) in oracle and I'm still getting the identifier too long error :+1: 

DBMS:
  oracle

Error:
  java.sql.SQLSyntaxErrorException: ORA-00972: identifier is too long


SQL:
  --HINT DISTRIBUTE_ON_KEY(concept_id)
CREATE TABLE kq38fltus_tmpach_ch_measurement
AS
SELECT ...


Also, one of the files in the Achilles\sql\sql_server\analyses directory : 1823.sql is missing a semicolon at the end which causes an error and the cessation of the code.  In my local version of the code,  I added the semicolon and it got past that problem, but then hit the above "name too long" error

**Comment by alondhe** [comment]
Hi @mgweiner -- can you try my fork but in your call to Achilles, set the tempAchillesPrefix to something with 1 letter, say "t"?

I added the missing semicolon for analysis 1823, and shortened the staging table names for the concept hierarchy tables.

`devtools::install_github("alondhe/Achilles")`

**Comment by mgweiner** [comment]
OK.. up and running again.  I'll let you know how it turns out in about 3 hours!

**Comment by t-abdul-basser** [comment]
Thanks @alondhe. Perhaps it might be even better, in the future, to create a branch (post-release-fix), make changes in the branch and then direct users to this branch.

**Comment by mgweiner** [comment]
Made it past the prior error, but now hit upon a new one :

DBMS:
  oracle

Error:
  java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended


SQL:
  DROP INDEX IF EXISTS idx_ar_aid on mark.ACHILLES_results (analysis_id)


which appears to come from  Achilles\sql\sql_server\post_processing\achilles_indices.sql

I've run the drop index command directly in Oracle and get the same error.  If an index exists, then 

DROP INDEX idx_ar_aid

works -- you dont need to specify the table, but it fails if the index doesnt exist,.  I see the "if exists" syntax is supposed to work (though possibly only within PL/SQL??), but when added to the query in my Oracle 12c instance, I am getting the "command not properly ended" statement.

**Comment by mgweiner** [comment]
I'm trying to work with the latest version on alondhe/Achilles, however, the install is behaving differently than other versions.  Because of a likely firewall issue, I have not been able to use 
`devtools::install_github("alondhe/Achilles")`

It hangs for a bit and then I see the following error:

Installation failed: Timeout was reached: Connection timed out after 10000 milliseconds

To work around this issue, I've been downloading and expanding the zip file of the earlier versions of Achilles and then issuing the following commands which seem to have the expected effect of creating an Achilles directory in my SAS library
```
source <- devtools:::source_pkg("C:\\Users\\weinermg\\Downloads\\Achilles-master")
install (source)
```
However with the latest release, the above steps give me the following error :

Installing Achilles
Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Timeout was reached: Connection timed out after 10000 milliseconds

Not sure where the curl business is coming from.  If I replace the "Achilles-master" with the download from the ODHSI\Achilles site, it will install, though I dont think that version has incorporated the latest changes we have discussed that you put in your forked version.
